### ISSUE TITLE
Consider removing `entranceMethod` and related properties

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg-screenshot-tester#11]
This part of the API is very specific to Custom Elements. More specifically: Custom Elements implemented with imperative OO APIs. It doesn't make sense for this general-purpose library to be so tightly coupled to this one pattern.

We already have the general-purpose `before` and `after` hooks, and that should cover all use cases. People can write their own little helpers to clean up their application-specific boilerplate.

**Comment by Lange** [comment]
@Hoishin I'd like your thoughts on this if you have a few minutes to spare

**Comment by Hoishin** [comment]
It makes sense to me too. Especially because there is alternative way to replace this for users.
