### ISSUE TITLE
Allow supplying a different version of Chromium

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg-screenshot-tester#5]
Often, a given graphics package will be built against a specific build of CEF, such as one shipped with a specific version of `obs-browser`. In these cases, it only makes sense to have screenshot tests which use the same revision of Chromium as the target environment.

We need to provide a way for consumers of this library to supply their own version of Chromium.

**Comment by Hoishin** [comment]
According to [this puppeteer FAQ](https://github.com/GoogleChrome/puppeteer#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy), specific version of puppeteer is only guaranteed to work on specific chromium version.
That would mean that users have to install their own puppeteer, but then that would break some API and make this library not work.

**Comment by Lange** [comment]
Yeah you're right, sounds like this is not feasible any time soon.

**Comment by Hoishin** [comment]
Now that I think about this, it would be possible if we make puppeteer optional/peer dependency and have users install themselves. It would also allow using puppeteer-firefox and other tools with same API as well.
